baseurl = "https://example.com/"
languageCode = "en-us"

# Change the default theme to be use when building the site with Hugo
theme = "relearn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

